import { npub, nevent, naddr, note } from '../src/nip19.js';
const pk = 'e8ed3798c6ffebffa08501ac39e271662bfd160f688f94c45d692d8767dd345a';
const got = npub(pk), want = 'npub1arkn0xxxll4llgy9qxkrncn3vc4l69s0dz8ef3zadykcwe7ax3dqrrh43w';
console.log('npub', got === want ? 'OK' : `MISMATCH ${got}`);
const ne = nevent('36f988e43ff1'.padEnd(64, '0'), { relays: ['wss://wheat.happytavern.co'], author: pk, kind: 0 });
console.log('nevent', ne.slice(0, 20) + '…', ne.length, 'chars');
console.log('naddr', naddr(30023, pk, 'hello', { relays: ['wss://wheat.happytavern.co'] }).slice(0, 24) + '…');
console.log('note', note(pk).slice(0, 12) + '…');
process.exit(got === want ? 0 : 1);
import { decodeEntity } from '../src/nip19.js';
const d1 = decodeEntity('npub1arkn0xxxll4llgy9qxkrncn3vc4l69s0dz8ef3zadykcwe7ax3dqrrh43w');
console.log('decode npub', d1.hex === pk ? 'OK' : 'MISMATCH');
const d2 = decodeEntity('nostr:' + ne); console.log('decode nevent', d2.hex.startsWith('36f988e43ff1') && d2.relays[0] === 'wss://wheat.happytavern.co' && d2.kind === 0 && d2.author === pk ? 'OK' : JSON.stringify(d2));
const d3 = decodeEntity(naddr(30023, pk, 'hello', { relays: ['wss://wheat.happytavern.co'] })); console.log('decode naddr', d3.d === 'hello' && d3.kind === 30023 && d3.hex === pk ? 'OK' : JSON.stringify(d3));
let bad = false; try { decodeEntity('npub1arkn0xxxll4llgy9qxkrncn3vc4l69s0dz8ef3zadykcwe7ax3dqrrh43x'); } catch (e) { bad = true; } console.log('corrupted npub rejected', bad ? 'OK' : 'NO');
